language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0
matrix:
    allow_failures:
        - php: 7.0
    fast_finish: true
sudo: false
services:
  - docker
cache:
  directories:
    - $HOME/.composer/cache
install:
  - composer install --no-interaction
  - travis_wait composer update --prefer-lowest --no-interaction
script:
  - ./vendor/bin/phpunit -c ./phpunit.xml --coverage-text
