#!/usr/bin/env php
<?php

define('CLI_ROOT', __DIR__);
error_reporting(E_ERROR | E_WARNING | E_PARSE);
if (file_exists(CLI_ROOT . '/vendor/autoload.php')) {
    require CLI_ROOT . '/vendor/autoload.php';
} else {
    echo "Composer autoload file not found.\n";
    echo "You need to run 'composer install'.\n";
    exit(1);
}
use mglaman\PlatformDocker\Application;
use Symfony\Component\Console\Input\ArgvInput;
$input = new ArgvInput();
$application = new Application();
$application->run($input);
